In [99]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [2]:
import numpy as np

In [109]:
#1 How many negative numbers are there?
len(a[a < 0 ])

4

In [110]:
#2 How many positive numbers are there
len(a[a > 0])

5

In [108]:
#3 How many even positive numbers are there?
positive_even_num = (a % 2 == 0) & (a > 0)
len(a[positive_even_num])

3

In [111]:
#4 If you were to add 3 to each data point, how many positive numbers would 
# there be?
a3 = a + 3 
len(a3[a3 > 0])

10

In [11]:
a3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [20]:
len(a3[a3 > 0])

10

In [18]:
#5 If you squared each number, what would the new mean and standard deviation be?
squared_a = a ** 2 

In [19]:
squared_a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [21]:
squared_a.mean()

74.0

In [24]:
np.std(squared_a)

144.0243035046516

In [102]:
np.std(a)

8.06225774829855

In [94]:
np.std(a3)


8.06225774829855

In [101]:
np.mean(a)

3.0

In [103]:
np.mean(a) ** 2

9.0

In [104]:
a.mean()

3.0

In [105]:
a.std()

8.06225774829855

In [106]:
a.std() **2

64.99999999999999

a - a.mean()

In [112]:
#6 A common statistical operation on a dataset is centering. 
#This means to adjust the data such that the mean of the data is 0. 
#
#This is done by subtracting the mean from each data point. 
#Center the data set. See this link for more on centering.

a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [100]:
# 7 Calculate the z-score for each data point. Recall that the z-score is given by:

(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [26]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

def sum_of_a(nums):
    total_list = 0 
    for num in nums:
        total_list = total_list + num
    return total_list
print(sum_of_a(a))

55


In [28]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

def min_of_a(nums):
    num_list = []
    for num in nums:
        num_list.append(num)
    return min(num_list)
print(min_of_a(a))

1


In [29]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

def max_of_a(nums):
    num_list = []
    for num in nums:
        num_list.append(num)
    return max(num_list)
print(max_of_a(a))

10


In [30]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

def mean_of_a(nums):
    total_list = 0 
    for num in nums:
        total_list = total_list + num
        avg = total_list / len(nums)
    return avg
print(mean_of_a(a))

5.5


In [31]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers 
# in the above list together

def product_of_a(nums):
    total = 1
    for i in nums:
        total *= i
    return (total)
print(product_of_a(a))

3628800


In [32]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

def squares_of_a(nums):
    squared_list = []
    for i in nums:
        squared_list.append(i**2)
    return (squared_list)
print(squares_of_a(a))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [34]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

def odds_in_a(nums):
    num_list = []
    for i in nums:
        if i % 2 != 0:
            num_list.append(i)
    return (num_list)
print(odds_in_a(a))

[1, 3, 5, 7, 9]


In [35]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

def evens_in_a(nums):
    num_list = []
    for i in nums:
        if i % 2 == 0:
            num_list.append(i)
    return (num_list)
print(evens_in_a(a))

[2, 4, 6, 8, 10]


In [36]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [37]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [38]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
print(sum_of_b)

33


In [39]:
b.sum()

33

In [40]:
# Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
print(min_of_b)

3


In [41]:
b.min()

3

In [42]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)

8


In [43]:
b.max()

8

In [44]:
# Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)

5.5


In [45]:
b.mean()

5.5

In [46]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(product_of_b)

20160


In [47]:
b.prod()

20160

In [48]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 

squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)

[9, 16, 25, 36, 49, 64]


In [49]:
b ** 2 

array([[ 9, 16, 25],
       [36, 49, 64]])

In [50]:
# Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

[3, 5, 7]


In [52]:
b[b % 2 !=0]

array([3, 5, 7])

In [53]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

[4, 6, 8]


In [54]:
b[b % 2 == 0]

array([4, 6, 8])

In [72]:
# Exercise 9 - print out the shape of the array b.

b.shape

(3, 2)

In [74]:
b.reshape(1,6)

array([[3, 6, 4, 7, 5, 8]])

In [56]:
# Exercise 10 - transpose the array b.

b = b.transpose()

In [57]:
b

array([[3, 6],
       [4, 7],
       [5, 8]])

In [73]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b.reshape(1, 6)

array([[3, 6, 4, 7, 5, 8]])

In [114]:
b.reshape(6,1)

array([[3],
       [6],
       [4],
       [7],
       [5],
       [8]])

In [61]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [62]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# Exercise 1 - Find the min, max, sum, and product of c.


c.min()

1

In [64]:
c.max()

9

In [65]:
c.sum()

45

In [66]:
c.prod()

362880

In [67]:
# Exercise 2 - Determine the standard deviation of c.

c.std()

2.581988897471611

In [68]:
# Exercise 3 - Determine the variance of c.

c.var()

6.666666666666667

In [71]:
# Exercise 4 - Print out the shape of the array c

c.shape

(3, 3)

In [70]:
# Exercise 5 - Transpose c and print out transposed result.

c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [76]:
# Exercise 6 - Get the dot product of the array c with c.

np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [77]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

sum(sum(c * c.transpose()))

261

In [113]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.
c.prod() * c.transpose().prod()

131681894400

In [78]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [79]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [80]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [81]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [82]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [83]:
# Exercise 4 - Find all the negative numbers in d

neg_numbers = d < 0
(d[neg_numbers])

array([-90, -30, -45, -45])

In [84]:
# Exercise 5 - Find all the positive numbers in d

pos_numbers = d > 0
(d[pos_numbers])

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [85]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [86]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [87]:
# Exercise 8 - Print out the shape of d.

d.shape

(3, 6)

In [88]:
# Exercise 9 - Transpose and then print out the shape of d.

d.transpose().shape

(6, 3)

In [89]:
# Exercise 10 - Reshape d into an array of 9 x 2

d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])